# Funding options shown in the repo's "Sponsor" button.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [JaceThings]
# patreon:
# ko_fi:
# buy_me_a_coffee:
# polar:
# custom: ["https://ja.mt"]
