/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatRouteImport } from './routes/what'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as MathRouteImport } from './routes/math'
import { Route as ChromeRouteImport } from './routes/chrome'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const WhatRoute = WhatRouteImport.update({
  id: '/what',
  path: '/what',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const ChromeRoute = ChromeRouteImport.update({
  id: '/chrome',
  path: '/chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chrome': typeof ChromeRoute
  '/math': typeof MathRoute
  '/playground': typeof PlaygroundRoute
  '/what': typeof WhatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chrome': typeof ChromeRoute
  '/math': typeof MathRoute
  '/playground': typeof PlaygroundRoute
  '/what': typeof WhatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chrome': typeof ChromeRoute
  '/math': typeof MathRoute
  '/playground': typeof PlaygroundRoute
  '/what': typeof WhatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/chrome'
    | '/math'
    | '/playground'
    | '/what'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/chrome'
    | '/math'
    | '/playground'
    | '/what'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/chrome'
    | '/math'
    | '/playground'
    | '/what'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ChromeRoute: typeof ChromeRoute
  MathRoute: typeof MathRoute
  PlaygroundRoute: typeof PlaygroundRoute
  WhatRoute: typeof WhatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what': {
      id: '/what'
      path: '/what'
      fullPath: '/what'
      preLoaderRoute: typeof WhatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chrome': {
      id: '/chrome'
      path: '/chrome'
      fullPath: '/chrome'
      preLoaderRoute: typeof ChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ChromeRoute: ChromeRoute,
  MathRoute: MathRoute,
  PlaygroundRoute: PlaygroundRoute,
  WhatRoute: WhatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
