#!/usr/bin/env tsx
/** Regenerates root CHANGELOG.md from per-package changelogs. Idempotent. */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packagesDir = join(repoRoot, "packages");
const rootChangelogPath = join(repoRoot, "CHANGELOG.md");
const RELEASE_DATES: Record<string, string> = {
  "0.3.0": "2026-04-24",
  "0.2.0": "2026-04-24",
  "0.1.0": "2026-04-23",
};
const PKG_ORDER = ["@lisse/react", "@lisse/vue", "@lisse/svelte", "@lisse/core"];
const H2 = /^##\s+(\d+\.\d+\.\d+(?:[-+][\w.]+)?)\s*$/;

type Entry = { packageName: string; packageDir: string; version: string; body: string };

function parseChangelog(markdown: string): Array<{ version: string; body: string }> {
  const entries: Array<{ version: string; body: string }> = [];
  let current: { version: string; body: string[] } | null = null;
  for (const line of markdown.split("\n")) {
    const match = line.match(H2);
    if (match) {
      if (current) entries.push({ version: current.version, body: current.body.join("\n").trim() });
      current = { version: match[1], body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }
  if (current) entries.push({ version: current.version, body: current.body.join("\n").trim() });
  return entries;
}

function summariseBody(body: string): string | null {
  const bullets: string[] = [];
  let buf: string[] = [];
  for (const line of body.split("\n")) {
    if (/^-\s/.test(line)) {
      if (buf.length) bullets.push(buf.join("\n"));
      buf = [line];
    } else if (buf.length) {
      buf.push(line);
    }
  }
  if (buf.length) bullets.push(buf.join("\n"));
  const meaningful = bullets.filter((b) => !/^-\s+Updated dependencies/i.test(b));
  if (meaningful.length === 0) return null;
  let text = meaningful[0].replace(/^-\s+/, "").trim();
  text = text.replace(/^\*\*?[Bb]reaking\*\*?:\s*/, "Breaking: ");
  text = text.replace(/^[0-9a-f]{7,40}:\s*/, "");
  const flat = text.split(/\n\s*\n/)[0].replace(/\s+/g, " ").trim();
  let summary = flat.match(/^(.+?[.!?])(?:\s+[A-Z`]|\s*$)/)?.[1] ?? flat;
  summary = summary.replace(/:$/, ".");
  return /[.!?]$/.test(summary) ? summary : `${summary}.`;
}

function compareVersions(a: string, b: string): number {
  const parse = (v: string) => v.split(/[.+-]/).map((p) => (/^\d+$/.test(p) ? Number(p) : p));
  const pa = parse(a);
  const pb = parse(b);
  for (let i = 0; i < Math.max(pa.length, pb.length); i += 1) {
    const ai = pa[i] ?? 0;
    const bi = pb[i] ?? 0;
    if (ai === bi) continue;
    if (typeof ai === "number" && typeof bi === "number") return ai - bi;
    return String(ai) < String(bi) ? -1 : 1;
  }
  return 0;
}

function comparePackages(a: string, b: string): number {
  const ia = PKG_ORDER.indexOf(a);
  const ib = PKG_ORDER.indexOf(b);
  if (ia !== -1 && ib !== -1) return ia - ib;
  if (ia !== -1) return -1;
  if (ib !== -1) return 1;
  return a.localeCompare(b);
}

function collectEntries(): Entry[] {
  const entries: Entry[] = [];
  for (const packageDir of readdirSync(packagesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => join(packagesDir, d.name))
    .sort()) {
    const changelogPath = join(packageDir, "CHANGELOG.md");
    const pkgJsonPath = join(packageDir, "package.json");
    if (!existsSync(changelogPath) || !existsSync(pkgJsonPath)) continue;
    const packageName = (JSON.parse(readFileSync(pkgJsonPath, "utf8")) as { name?: string }).name;
    if (!packageName) continue;
    for (const { version, body } of parseChangelog(readFileSync(changelogPath, "utf8"))) {
      entries.push({ packageName, packageDir, version, body });
    }
  }
  return entries;
}

function render(entries: Entry[]): string {
  const byVersion = new Map<string, Entry[]>();
  for (const entry of entries) {
    (byVersion.get(entry.version) ?? byVersion.set(entry.version, []).get(entry.version)!).push(entry);
  }
  const out = [
    "# Changelog",
    "",
    "Aggregate release notes across the `@lisse/*` packages. Per-package detail lives in each package's own `CHANGELOG.md`.",
    "",
    "<!-- This file is generated by scripts/update-root-changelog.ts. Do not edit by hand. -->",
    "",
  ];
  for (const version of [...byVersion.keys()].sort((a, b) => compareVersions(b, a))) {
    const sectionStart = out.length;
    out.push(RELEASE_DATES[version] ? `## ${version} (${RELEASE_DATES[version]})` : `## ${version}`, "");
    let wrote = 0;
    for (const entry of (byVersion.get(version) ?? []).sort((a, b) =>
      comparePackages(a.packageName, b.packageName))) {
      const summary = summariseBody(entry.body);
      if (summary === null) continue;
      const rel = entry.packageDir.replace(repoRoot, "").replace(/^\/+/, "").split(/[/\\]/).join("/");
      out.push(`- [${entry.packageName}](./${rel}/CHANGELOG.md#${version.replace(/\./g, "")}): ${summary}`);
      wrote += 1;
    }
    if (wrote === 0) out.length = sectionStart;
    else out.push("");
  }
  return out.join("\n").replace(/\n+$/, "\n");
}

writeFileSync(rootChangelogPath, render(collectEntries()), "utf8");
